# Generated by Django 4.0.5 on 2022-07-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='enlace',
            field=models.URLField(blank=True, default='/Producto/BorreEstoYAquíEscribaElIdDeCategoría', null=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idnumcatp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.catalogo', verbose_name='Disponible en categoría'),
        ),
    ]
