# Generated by Django 4.0.5 on 2022-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_catalogo_delete_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=200, verbose_name='Nombre del catálogo')),
                ('detallep', models.TextField(verbose_name='Descripción')),
                ('imagenp', models.ImageField(upload_to='ProyectosImagenes', verbose_name='Imagen del catálogo')),
                ('agregadop', models.DateTimeField(auto_now_add=True, verbose_name='Fecha agregado')),
                ('modificadop', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-agregadop'],
            },
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha agregado'),
        ),
    ]
