# Generated by Django 4.0.5 on 2022-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_catalogo_enlace_producto_idnumcatp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='enlace',
            field=models.CharField(default='/Producto/<django.db.models.fields.AutoField>', max_length=200, verbose_name='Enlace'),
        ),
    ]
