# Generated by Django 4.0.5 on 2022-08-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_catalogo_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='compradop',
            field=models.IntegerField(default=0, verbose_name='Total comprado'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='enlace',
            field=models.CharField(default='/Producto/0', max_length=200, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='idnumcat',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Id de la categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idnumcatp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.catalogo', verbose_name='Disponible en categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idnumprod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto'),
        ),
    ]
