# Generated by Django 4.0.5 on 2022-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_catalogo_idnumcat_producto_idnumprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marcap',
            field=models.TextField(default='', max_length=100, verbose_name='Marca del dispositivo'),
        ),
    ]
