# Generated by Django 4.0.5 on 2022-08-08 04:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_catalogo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='compradop',
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nombrep', editable=False, populate_from='titulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nombrep', editable=False, populate_from='nombrep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='vendidop',
            field=models.IntegerField(default=0, verbose_name='Total vendidos'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='enlace',
            field=models.CharField(default='/Producto/<django.db.models.fields.IntegerField>', max_length=200, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idnumcat',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la categoría'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(default='Nombre de categoría', max_length=200, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombrep',
            field=models.CharField(default='Nombre de producto', max_length=200, verbose_name='Nombre del producto'),
        ),
    ]
