# Generated by Django 4.0.5 on 2022-08-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_producto_compradop_categoria_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
