# Generated by Django 4.0.5 on 2022-08-08 04:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_categoria_slug_remove_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='titulo', editable=False, populate_from='titulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nombrep', editable=False, populate_from='nombrep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombrep',
            field=models.CharField(max_length=200, verbose_name='Nombre del producto'),
        ),
    ]
