# Generated by Django 4.0.5 on 2022-08-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_categoria_slug_producto_slug_alter_categoria_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='enlace',
        ),
        migrations.AlterField(
            model_name='producto',
            name='marcap',
            field=models.CharField(max_length=100, verbose_name='Marca del producto'),
        ),
    ]
