# Generated by Django 4.0.5 on 2022-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_categoria_enlace_alter_producto_marcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='EnLista',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preciop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Precio del producto'),
        ),
    ]
