# Generated by Django 4.0.5 on 2022-08-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_producto_enlista_alter_producto_preciop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='EnLista',
        ),
    ]
